export const userActionTypes = {
    LOGIN_START: 'LOGIN_START',
    REGISTER_START: 'REGISTER_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT: 'LOGOUT',
    SET_TOKEN: 'SET_TOKEN',
    SET_USER: 'SET_USER',
    SET_USER_DISPLAY_NAME: 'SET_USER_DISPLAY_NAME',
    REMOVE_TOKEN: 'REMOVE_TOKEN',
    RESET_ERROR: 'RESET_ERROR',
    SET_USER_IMAGE: 'SET_USER_IMAGE',
    UPDATE_USER: 'UPDATE_USER'
};